export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './banks.service';
import { BanksService } from './banks.service';
export * from './tokens.service';
import { TokensService } from './tokens.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AccountsService, BanksService, TokensService, TransactionsService, UsersService];
