/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductType } from './productType';


export interface BankAccount { 
    id?: number;
    code?: string | null;
    balance?: number;
    creditLimit?: number;
    title?: string | null;
    bankId?: number | null;
    selectedTariffId?: number | null;
    productId?: number | null;
    type?: ProductType;
    opened?: Date | null;
}

