/**
 * SlidFinance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CashbackCategoryType } from './cashbackCategoryType';


export interface CashbackCategory { 
    id?: number;
    title?: string;
    description?: string;
    tariffId?: number;
    cashbackLimit?: number;
    type?: CashbackCategoryType;
}
