/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashbackCategoryType } from './cashbackCategoryType';


export interface CashbackCategory { 
    id?: number;
    title?: string | null;
    description?: string | null;
    tariffId?: number;
    cashbackLimit?: number;
    type?: CashbackCategoryType;
}

