/**
 * SlidFinance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MccCategory = 'None' | 'ContractServices' | 'ContractWork' | 'WholesaleDistributorsAndManufacturers' | 'Airlines' | 'CarRent' | 'Hotels' | 'Transportation' | 'Utilities' | 'ServiceProviders' | 'WholesaleSuppliersAndManufacturers' | 'RetailSale' | 'CarsAndOtherVehicles' | 'ClothingStores' | 'VariousShops' | 'PostalTelephoneProviders' | 'IndividualServiceProviders' | 'BusinessServices' | 'RepairServices' | 'Entertainment';

export const MccCategory = {
    None: 'None' as MccCategory,
    ContractServices: 'ContractServices' as MccCategory,
    ContractWork: 'ContractWork' as MccCategory,
    WholesaleDistributorsAndManufacturers: 'WholesaleDistributorsAndManufacturers' as MccCategory,
    Airlines: 'Airlines' as MccCategory,
    CarRent: 'CarRent' as MccCategory,
    Hotels: 'Hotels' as MccCategory,
    Transportation: 'Transportation' as MccCategory,
    Utilities: 'Utilities' as MccCategory,
    ServiceProviders: 'ServiceProviders' as MccCategory,
    WholesaleSuppliersAndManufacturers: 'WholesaleSuppliersAndManufacturers' as MccCategory,
    RetailSale: 'RetailSale' as MccCategory,
    CarsAndOtherVehicles: 'CarsAndOtherVehicles' as MccCategory,
    ClothingStores: 'ClothingStores' as MccCategory,
    VariousShops: 'VariousShops' as MccCategory,
    PostalTelephoneProviders: 'PostalTelephoneProviders' as MccCategory,
    IndividualServiceProviders: 'IndividualServiceProviders' as MccCategory,
    BusinessServices: 'BusinessServices' as MccCategory,
    RepairServices: 'RepairServices' as MccCategory,
    Entertainment: 'Entertainment' as MccCategory
};
