/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Rule { 
    id?: number;
    order?: string | null;
    accountId?: number | null;
    categoryId?: number | null;
    description?: string | null;
    mccId?: number | null;
    bankCategory?: string | null;
}

