/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeTransactionCount } from './seTransactionCount';


export class SeAccountExtra { 
  account_name: string | null;
  account_number: string | null;
  assets: Array<string> | null;
  available_amount: number | null;
  blocked_amount: number | null;
  card_type: string | null;
  cards: Array<string> | null;
  client_name: string | null;
  closing_balance: number | null;
  credit_limit: number | null;
  current_date: Date | null;
  current_time: Date;
  expiry_date: string | null;
  iban: string | null;
  interest_rate: number | null;
  next_payment_amount: number | null;
  next_payment_date: string | null;
  open_date: string | null;
  opening_balance: number | null;
  partial: boolean | null;
  sort_code: string | null;
  statement_cut_date: Date | null;
  status: string | null;
  swift: string | null;
  total_payment_amount: number | null;
  transactions_count: SeTransactionCount | null;
  payment_type: string | null;
  cashback_amount: number | null;
  unit_price: number | null;
  units: number | null;
  indicative_unit_price: number | null;
  interest_income: number | null;
  interest_amount: number | null;
  fund_holdings: object | null;
  premium_frequency: string | null;
  policy_status: string | null;
  life_assured_name: string | null;
  premium_amount: number | null;
  financial_consultant: string | null;
  total_reversionary_bonus: number | null;
  gross_surrender: number | null;
  guaranteed_gross_surrender: number | null;
  reversionary_bonus_cash_value: number | null;
  owned_policy_amount: number | null;
  policy_loan_limit: number | null;
  policy_converted_to_paid_up: number | null;
  paid_up_conversion_reversionary_bonus: number | null;
  policy_components: object | null;
  last_posted_transaction_id: string | null;
}

