/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeTransactionCount } from './seTransactionCount';


export interface SeAccountExtra { 
    accountName?: string | null;
    accountNumber?: string | null;
    assets?: Array<string> | null;
    availableAmount?: number | null;
    blockedAmount?: number | null;
    cardType?: string | null;
    cards?: Array<string> | null;
    clientName?: string | null;
    closingBalance?: number | null;
    creditLimit?: number | null;
    currentDate?: Date | null;
    currentTime?: Date;
    expiryDate?: string | null;
    iban?: string | null;
    interestRate?: number | null;
    nextPaymentAmount?: number | null;
    nextPaymentDate?: string | null;
    openDate?: string | null;
    openingBalance?: number | null;
    partial?: boolean | null;
    sortCode?: string | null;
    statementCutDate?: Date | null;
    status?: string | null;
    swift?: string | null;
    totalPaymentAmount?: number | null;
    transactionsCount?: SeTransactionCount | null;
    paymentType?: string | null;
    cashbackAmount?: number | null;
    unitPrice?: number | null;
    units?: number | null;
    indicativeUnitPrice?: number | null;
    interestIncome?: number | null;
    interestAmount?: number | null;
    fundHoldings?: object | null;
    premiumFrequency?: string | null;
    policyStatus?: string | null;
    lifeAssuredName?: string | null;
    premiumAmount?: number | null;
    financialConsultant?: string | null;
    totalReversionaryBonus?: number | null;
    grossSurrender?: number | null;
    guaranteedGrossSurrender?: number | null;
    reversionaryBonusCashValue?: number | null;
    ownedPolicyAmount?: number | null;
    policyLoanLimit?: number | null;
    policyConvertedToPaidUp?: number | null;
    paidUpConversionReversionaryBonus?: number | null;
    policyComponents?: object | null;
    lastPostedTransactionId?: string | null;
}

