/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeStage } from './seStage';


export class SeAttempt { 
  api_mode: string | null;
  api_version: string | null;
  automatic_fetch: boolean | null;
  user_present: boolean | null;
  categorization: string | null;
  created_at: Date | null;
  customer_last_logged_at: Date | null;
  custom_fields: object | null;
  daily_refresh: boolean | null;
  device_type: string | null;
  remote_ip: string | null;
  exclude_accounts: Array<string> | null;
  fail_at: Date | null;
  fail_error_class: string | null;
  fail_message: string | null;
  fetch_scopes: Array<string> | null;
  finished: boolean | null;
  finished_recent: boolean | null;
  from_date: Date | null;
  id: string | null;
  interactive: boolean | null;
  partial: boolean | null;
  store_credentials: boolean | null;
  success_at: Date | null;
  to_date: Date | null;
  updated_at: Date | null;
  show_consent_confirmation: boolean | null;
  include_natures: Array<string> | null;
  last_stage: SeStage | null;
  stages: Array<SeStage> | null;
}

