/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeStage } from './seStage';


export interface SeAttempt { 
    apiMode?: string | null;
    apiVersion?: string | null;
    automaticFetch?: boolean | null;
    userPresent?: boolean | null;
    categorization?: string | null;
    createdAt?: Date | null;
    customerLastLoggedAt?: Date | null;
    customFields?: object | null;
    dailyRefresh?: boolean | null;
    deviceType?: string | null;
    remoteIp?: string | null;
    excludeAccounts?: Array<string> | null;
    failAt?: Date | null;
    failErrorClass?: string | null;
    failMessage?: string | null;
    fetchScopes?: Array<string> | null;
    finished?: boolean | null;
    finishedRecent?: boolean | null;
    fromDate?: Date | null;
    id?: string | null;
    interactive?: boolean | null;
    partial?: boolean | null;
    storeCredentials?: boolean | null;
    successAt?: Date | null;
    toDate?: Date | null;
    updatedAt?: Date | null;
    showConsentConfirmation?: boolean | null;
    includeNatures?: Array<string> | null;
    lastStage?: SeStage | null;
    stages?: Array<SeStage> | null;
}

