/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeAttempt } from './seAttempt';


export interface SeConnection { 
    countryCode?: string | null;
    createdAt?: Date | null;
    customerId?: string | null;
    dailyRefresh?: boolean | null;
    id?: string | null;
    showConsentConfirmation?: boolean | null;
    lastConsentId?: string | null;
    lastAttempt?: SeAttempt | null;
    lastSuccessAt?: Date | null;
    nextRefreshPossibleAt?: Date | null;
    providerId?: string | null;
    providerCode?: string | null;
    providerName?: string | null;
    status?: string | null;
    storeCredentials?: boolean | null;
    updatedAt?: Date | null;
}

