/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeAttempt } from './seAttempt';


export class SeConnection { 
  country_code: string | null;
  created_at: Date | null;
  customer_id: string | null;
  daily_refresh: boolean | null;
  id: string | null;
  show_consent_confirmation: boolean | null;
  last_consent_id: string | null;
  last_attempt: SeAttempt | null;
  last_success_at: Date | null;
  next_refresh_possible_at: Date | null;
  provider_id: string | null;
  provider_code: string | null;
  provider_name: string | null;
  status: string | null;
  store_credentials: boolean | null;
  updated_at: Date | null;
}

