/**
 * SlidFinance
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SeStage { 
    createdAt?: Date | null;
    id?: string | null;
    interactiveFieldsName?: Array<string> | null;
    interactiveHtml?: string | null;
    name?: string | null;
    updatedAt?: Date | null;
}

